name: mirror_me
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  camera: ^0.11.0+2
  cloud_firestore: ^5.4.4
  equatable: ^2.0.5
  firebase_auth: ^5.3.0
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.0
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_staggered_animations: ^1.1.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  share_plus: ^10.0.3
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
